[package]
name = "native-host"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
byteorder = "1.4"
anyhow = "1.0"
log = "0.4"
env_logger = "0.10"
